e2b-dev/awesome-ai-agents

- README.md
Added [Proficient AI](https://proficientai.com) on Vasek's recommendation
> Added Proficient AI

- README.md
> Update README.md with yAgents

- README.md
This PR fixes a typo in the BitBuilder section.
Thanks for including us!
> BitBuilder: Typo Fix

- README.md
I updated Tweet, GitHub, Replit, and Author to each BabyAGI mod's link.
- Reference: https://twitter.com/tereza_tizkova/status/1673094523822690304
> Updated the links for the BabyAGI mods

- .vscode/settings.json
- README.md
GPT-Runner allow you conversations with your files and manage and run your AI presets!
Github: https://github.com/nicepkg/gpt-runner
> Add GPT Runner

- README.md
Added our product "Heights Platform" to README.md
> Add Heights Platform

- README.md
https://github.com/ennucore/clippy/
The purpose of Clippy is to develop code for or with the user. It can plan, write, debug, and test some projects autonomously. For harder tasks, the best way to use it is to look at its work and provide feedback to it.
> Add Clippy - a code assistant

- README.md
Add encode - a fully autonomous software engineer
> Add encode

- README.md
Hey @tizkovatereza,
Amazing landscape!
I added the description for Lemon Agent in the `Readme.md`.
For the `.png` landscape please feel free to use the following logo:
From a category perspective 'Open Source' - 'Build Your Own' makes most sense in my opinion.
> Add Lemon Agent to landscape

- README.md
1. Cody of ajhous44 - https://github.com/ajhous44/cody
An AI assistant designed to let you interactively query your codebase using natural language. By utilizing vector embeddings, chunking, and OpenAI's language models, Cody can help you navigate through your code in an efficient and intuitive manner.
2. Mentat - https://github.com/biobootloader/mentat
Mentat is the AI tool that assists you with any coding task, right from your command line.
Unlike Copilot, Mentat coordinates edits across multiple locations and files. And unlike ChatGPT, Mentat already has the context of your project - no copy and pasting required!
> Add Cody of ajhous44 and Mentat AI

- README.md
Hey friends, I've updated your agent list with the latest mod of BabyAGI, including all relevant links.
> Added BabyElfAGI to the list of agents

- README.md
DevOpsGPT: AI-Driven Software Development Automation Solution
> Added DevOpsGPT

- README.md
Hi I'm Vinod - Founder of TalktoData AI Agent.
I would like to add this agent under Data Analytics section of the Agents
> Added TalktoData AI Agent

- README.md
Cursor : The AI-first Code Editor. Build software faster in an editor designed for pair-programming with AI.
> Add cursor - The AI-first Code Editor

- README.md
This PR adds [AilaFlow](https://ailaflow.com/) to the list.
> Add ailaflow.com

- README.md
Hi, 
I'm the founder of IX.  This PR adds it to the agents list.
> Adding Agent IX to the list

- README.md
https://github.com/langroid/langroid
A new Multi-Agent LLM Framework.
> Add Langroid Multi-Agent Framework

- README.md
Hi, i am a collaborator of XAgent, this pr adds XAgent to the list.
And i wonder how can we be added into landscape.png? I already filled in the form.
> Add XAgent

- README.md
Hi, we are the XLang team from the University of Hong Kong, we would like to introduce OpenAgents work. Check it out:
abs: https://arxiv.org/abs/2310.10634
pdf: https://arxiv.org/pdf/2310.10634.pdf
Code: https://github.com/xlang-ai/OpenAgents
Demos: https://chat.xlang.ai/
Docs: https://docs.xlang.ai/
Hope you and your audience like it!
> Update XLang OpenAgents

- README.md
fix https://github.com/e2b-dev/awesome-ai-agents/issues/62
> add AutoGen

- README.md
Please consider, thank you! This is for http://taskade.com/
Our new Custom Agents announcement here: https://twitter.com/Taskade/status/1724145860324528525 and https://www.taskade.com/blog/custom-ai-agents-gpts/
> Added Taskade AI Agents

- README.md
Would you mind taking a look at these agents? @sqs @abdshomad @deppp @kreneskyp
> add a few agents

- README.md
Hi there, I've been a collaborator on `bumpgen`, an open source AI agent to upgrade npm dependencies and fix their breaking changes. Seems like it would be a good fit for this list, so I'd love to add it!
> Add bumpgen

- README.md
Hi @tizkovatereza, I added BrainSoup, a native multi-LLM and multi-agent client for Windows. Thanks for creating this awesome list!
> Add BrainSoup to the list

- README.md
Adding MutahunterAI to open source list
> adding mutahunter to open source

- README.md
We built a VSCode extension that automatically debugs backend code and suggest fixes called Blinky! We'd love to be included on the awesome-ai-agents list so folks can try it out!
> Added Blinky, an open-source AI debugging agent

- README.md
> Add data-to-paper
